name = "EcoNetPlot"
uuid = "cb759ccd-645c-4f60-9a03-02ab6c6b6960"
authors = ["Ismaël Lajaaiti <ismael.lajaaiti@gmail.com>"]
version = "0.1.0"

[deps]
EcologicalNetworksDynamics = "2fd9189a-c387-4076-88b7-22b33b5a4388"

[compat]
EcologicalNetworksDynamics = "0.3.0"
